dbt_incremental:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: etnsirn-hc61829

      # User/password auth
      user: garthjon
      password: Motdepasse1978

      role: ACCOUNTADMIN
      database: DBT_ETL
      warehouse: COMPUTE_WH
      schema: STAGING
      threads: 4
      client_session_keep_alive: False
      query_tag: anything

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None